//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using NUnit.Framework;
using UnityEngine;
using System;

namespace Thomsen.FPMITAPrison 
{
	[TestFixture()]
	public class MethHeadBleedingTest
	{
		[Test()]
		public void shouldTransitionToSansShankOnButtonPressA ()
		{ 
			MethHeadBleeding methHeadBleeding = new MethHeadBleeding();

			var state = methHeadBleeding.handleInput (KeyCode.A);

			Assert.IsInstanceOf<SansShank> (state);
		}

		[Test()]
		public void shouldTransitionToStabbedInBrainOnButtonPressB ()
		{
			MethHeadBleeding methHeadBleeding = new MethHeadBleeding ();

			var state = methHeadBleeding.handleInput (KeyCode.B);

			Assert.IsInstanceOf<StabbedInBrain> (state);
		}

		[Test()]
		public void shouldTransitionToHoleInNeckOnButtonPressC ()
		{
			MethHeadBleeding methHeadBleeding = new MethHeadBleeding ();
			
			var state = methHeadBleeding.handleInput (KeyCode.C);
			
			Assert.IsInstanceOf<HoleInNeck> (state);
		}
		[Test()]
		public void shouldStayMethHeadBleedingOnButtonPressAnyOther ()
		{
			MethHeadBleeding methHeadBleeding = new MethHeadBleeding ();

			var state = methHeadBleeding.handleInput (KeyCode.Z);

			Assert.IsInstanceOf<MethHeadBleeding> (state);
		}
	}
}

