//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using NUnit.Framework;
using UnityEngine;
using System;

namespace Thomsen.FPMITAPrison 
{
	[TestFixture()]
	public class SansMethTest
	{
		[Test()]
		public void shouldTransitionToMethHeadBleedingOnButtonPressA ()
		{ 
			SansMeth sansMeth = new SansMeth();

			var state = sansMeth.handleInput (KeyCode.A);

			Assert.IsInstanceOf<MethHeadBleeding> (state);
		}

		[Test()]
		public void shouldTransitionToBleedingNeckOnButtonPressB ()
		{
			InCell inCell = new InCell();
			
			var state = inCell.handleInput (KeyCode.B);
			
			Assert.IsInstanceOf<BleedingNeck> (state);
		}

		[Test()]
		public void shouldTransitionToHangingDeadOnButtonPressC ()
		{
			InCell inCell = new InCell();
			
			var state = inCell.handleInput (KeyCode.C);
			
			Assert.IsInstanceOf<HangingDead> (state);
		}
		[Test()]
		public void shouldStayInCellOnButtonPressAnyOther ()
		{
			InCell inCell = new InCell();

			var state = inCell.handleInput (KeyCode.Z);

			Assert.IsInstanceOf<InCell> (state);
		}
	}
}

