//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using NUnit.Framework; 
using System;
using UnityEngine;

namespace Thomsen.FPMITAPrison
{
	[TestFixture()]
	public class TextControllerTest
	{
		[Test()]
		public void shouldAcceptInput ()
		{ 
			//BleedingNeck bleedingNeck = new BleedingNeck();

			//var state = bleedingNeck.handleInput (KeyCode.Escape);

			//Assert.IsInstanceOf<StateStart> (state);
		}

		[Test()]
		public void shouldUpdateTextOnStateChange ()
		{ 
			//BleedingNeck bleedingNeck = new BleedingNeck();
			
			//var state = bleedingNeck.handleInput (KeyCode.Escape);
			
			//Assert.IsInstanceOf<StateStart> (state);
		}
	}
}

