//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using NUnit.Framework; 
using System;
using UnityEngine;

namespace Thomsen.FPMITAPrison
{
	public class BleedingNeck : State
	{
		#region State implementation
		public string printOptions ()
		{
			throw new NotImplementedException ();
		}
		public State handleInput (KeyCode code)
		{
			throw new NotImplementedException ();
		}
		#endregion
	}

}

