//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using UnityEngine;

namespace Thomsen.FPMITAPrison
{
	public class BleedingNeck : State
	{
		#region State implementation
		public string printOptions ()
		{
			return "You stab yourself in the neck, throw the shank down, and call for help.  The guards come, see the bloody shank, and decide to let you die.  You die."+
				"\n\nPress Escape to start over.";
		}
		public State handleInput (KeyCode code)
		{
			if (code == KeyCode.Escape) {
				return new StateStart();
			} else return new BleedingNeck();
		}
		#endregion
	}

}

