//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using UnityEngine;
using System;

namespace Thomsen.FPMITAPrison
{
	public class ChokedOnBlood : State
	{
		#region State implementation
		public string printOptions ()
		{
			return "As you duck down for an uppercut stab to the taint, the tweaker punches you in the face and you miss the taint but slice his femoral artery. "+
				"You get sprayed in the face with so much blood that you start choking on the blood.  You die.\n\nPress Escape to start over.";
		}
		public State handleInput (KeyCode code)
		{
			if (code == KeyCode.Escape) {
				return new StateStart ();
			} else
				return new ChokedOnBlood();
		}
		#endregion
	}

}

