//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using UnityEngine;

namespace Thomsen.FPMITAPrison
{
	public class HangingDead : State
	{
		#region State implementation
		public string printOptions ()
		{
			return "You die with a dirty towel around your neck and the tweaker steals your meth. \n\nPress Escape to start over.";
		}
		public State handleInput (KeyCode code)
		{
			if (code == KeyCode.Escape) {
				return new StateStart ();
			} else if (code == KeyCode.Z) {
				return new HangingDead();
			}
			else return new HangingDead();
		}
		#endregion
	}

}

