//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using UnityEngine;

namespace Thomsen.FPMITAPrison

{
	public class InCell : State
	{
		#region State implementation
		public String printOptions ()
		{
			return "What would you like to do? \n\nPress \"A\" to give your meth-head cellmate all the meth. \nPress \"B\" to shank yourself and call for help.  " +
				"\nPress \"C\" to hang yourself with your towel.";
		}
		public State handleInput (KeyCode code)
		{
			if (code == KeyCode.A) {
				return new SansMeth();
			}
			if (code == KeyCode.B) {
				return new BleedingNeck();
			}
			if (code == KeyCode.C) {
				return new HangingDead();
			}
			return null;
		}
		#endregion
	}

}

