// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using UnityEngine;
using System;

namespace Thomsen.FPMITAPrison
{
	public class SansShank : State
	{
		#region State implementation
		public string printOptions ()
		{
			return "You hand your cellmate the shank just as the guards show up to investigate.  The guards see what is happening, and decide to let him die and kill you too.  You die."+
				"\n\nPress Escape to start over.";
		}
		public State handleInput (KeyCode code)
		{
			if (code == KeyCode.Escape) {
				return new StateStart();
			} else
				return new SansShank();
		}
		#endregion
	}

}

