//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using UnityEngine;
using System;

namespace Thomsen.FPMITAPrison
{
	public class StabbedInBrain : State
	{
		#region State implementation
		public string printOptions ()
		{
			return "You try to stab the tweaker again and slip and fall on the knife, which stabs you in the brain.  You die. \n\nPress Escape to start over.";
		}
		public State handleInput (KeyCode code)
		{
			if (code == KeyCode.Escape) {
				return new StateStart();
			} else
				return new StabbedInBrain();
		}
		#endregion
	}

}

