//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using NUnit.Framework; 
using System;
using UnityEngine;

namespace StateStartTest
{
	public class StateStart : State
	{
		#region State implementation
		public String printOptions ()
		{
			return "Welcome to federal pound me in the ass prison.  You can either try to escape, or safely live out your days as " +
				"an upstanding federal prisoner. You have in your possession a prison shank, a towel and a bunch of meth. \n\n" +
					"Press \"E\" try to escape.\nPress \"L\" to live out your sentence.";
		}
		public State handleInput (KeyCode code)
		{
			if (code == KeyCode.E) {
				return new InCell ();
			}
			if (code == KeyCode.L) {
				return new LifeFail();
			}
			return new StateStart ();
		}
		#endregion
	}

}

